vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        image:
            uri_prefix: /images
            upload_destination: '%kernel.project_dir%/public/uploads/images'
            # Will rename uploaded files using a uniqueid as a prefix.
            namer: Vich\UploaderBundle\Naming\OrignameNamer
        tarot_image:
            uri_prefix: /tarot_images
            upload_destination: '%kernel.project_dir%/public/uploads/tarot_images'
            # Will rename uploaded files using a uniqueid as a prefix.
            namer: Vich\UploaderBundle\Naming\OrignameNamer

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
